const fs = require('fs');

let content = fs.readFileSync('src/context/LanguageContext.tsx', 'utf8');

const newES = `
    // ==== FASE 3: NUEVAS PAGINAS ====
    'donate.hero.title': 'Invierte en el Reino',
    'donate.hero.subtitle': 'Con tu aporte financias telemedicina de emergencia y soporte médico encriptado para obreros en la Ventana 10/40 y zonas de alta restricción.',
    'donate.freq.once': 'Única Vez',
    'donate.freq.monthly': 'Mensual',
    'donate.btn': 'Donar Ahora con MercadoPago',
    
    'volunteer.hero.title': 'Sirve con Nosotros',
    'volunteer.hero.subtitle': 'Usa tus dones médicos y técnicos para sostener la retaguardia de la Gran Comisión.',
    'volunteer.models.title': 'Modelos de Reclutamiento',
    'volunteer.models.subtitle': 'Ofrecemos opciones flexibles para que puedas integrarte al equipo según tu disponibilidad y llamado.',
    'volunteer.models.ft.title': 'Full-Time Corps',
    'volunteer.models.ft.desc': 'Compromiso a largo plazo (3+ años) para médicos de carrera y misioneros de salud que desean dedicar su vida al cuidado de obreros transculturales.',
    'volunteer.models.st.title': 'Reserve Corps (Short-Term)',
    'volunteer.models.st.desc': 'Servicio flexible de 2 semanas a 1 año para cubrir relevos de emergencia en hospitales y clínicas de misión en momentos críticos.',
    'volunteer.spec.title': 'Especialidades Prioritarias',
    'volunteer.spec.subtitle': '¿Quiénes son los más necesitados en este momento?',
    'volunteer.apply': 'Aplicar Ahora',
    
    'prayer.hero.title': 'Red de Intercesión',
    'prayer.hero.subtitle': 'Sosteniendo los brazos de quienes están en la brecha. Tu oración es nuestra principal línea de defensa y cuidado.',
    'prayer.impact.title': 'Impacto Global de Oración',
    'prayer.impact.subtitle': 'Peticiones levantadas al Señor por nuestra red',
    'prayer.btn.prayed': 'Ya Oraste',
    'prayer.btn.pray': 'He Orado por Esto',
    
    'stories.hero.title': 'Historias e Impacto',
    'stories.hero.subtitle': 'Conoce de primera mano cómo el cuidado de la salud integral está transformando el campo misionero global.',
    'stories.patients.title': 'Historias de Pacientes',
    'stories.patients.desc': 'Testimonios de misioneros y familias que han recibido asistencia médica, psicológica o de telemedicina en situaciones críticas. Historias de gracia, resiliencia y provisión.',
    'stories.patients.link': 'Leer Testimonios',
    'stories.reality.title': 'La Realidad del Campo',
    'stories.reality.desc': 'Explora los desafíos reales de salud, aislamiento, logística y seguridad (OPSEC) que enfrentan los obreros transculturales en la Ventana 10/40.',
    'stories.reality.link': 'Conocer la Realidad',
    
    'hub.hero.title': 'Participa y Haz la Diferencia',
    'hub.hero.subtitle': 'Existen muchas formas de ser la retaguardia de la Gran Comisión. Encuentra tu lugar en nuestra red internacional de cuidado.',
    'hub.donate.title': 'Donar',
    'hub.donate.desc': 'Sostén la retaguardia de los misioneros financiando atenciones médicas, evacuaciones y desarrollo de telemedicina segura.',
    'hub.volunteer.title': 'Voluntariado',
    'hub.volunteer.desc': 'Usa tu profesión (Médicos, Enfermeros, TI) para brindar soporte especializado a corto o largo plazo.',
    'hub.church.title': 'Iglesias Asociadas',
    'hub.church.desc': 'Involucra a tu congregación en la misión de cuidar a quienes fueron enviados a través de ofrendas, oración y concientización.',
    'hub.prayer.title': 'Red de Oración',
    'hub.prayer.desc': 'Intercede por los desafíos de salud física, mental y espiritual que enfrentan los obreros en las naciones.',
    'hub.link': 'Saber Más',
    
    'church.hero.title': 'Iglesias Asociadas',
    'church.hero.subtitle': 'La Iglesia Local es la protagonista de la Gran Comisión. Nosotros somos su retaguardia técnica y médica.',
    'church.axes.title': 'Tres Ejes de Colaboración',
    'church.axes.pray.title': 'Oramos',
    'church.axes.pray.desc': 'Conecta a tu congregación con motivos reales y confidenciales del campo. Intercede por la salud y protección de los obreros transculturales.',
    'church.axes.give.title': 'Damos',
    'church.axes.give.desc': 'Inviertan como iglesia en la creación de infraestructura médica resiliente y segura. Cada aporte patrocina atención gratuita para los misioneros.',
    'church.axes.go.title': 'Vamos',
    'church.axes.go.desc': 'Moviliza a los profesionales de salud de tu iglesia para servir a corto o largo plazo usando sus dones al servicio del Reino.',
    'church.form.title': 'Invita a MMC a tu Iglesia',
    'church.form.subtitle': 'Solicita una presentación, conferencia o taller sobre Cuidado Integral y Salud Misionera.',
    'church.form.submit': 'Enviar Solicitud',
    
    'corporate.hero.title': 'Empresas e Instituciones',
    'corporate.hero.subtitle': 'Programa "Partners in Care": Responsabilidad Social Empresarial enfocada en salud global de alto riesgo.',
    'corporate.impact.title': 'Impacto Corporativo Real',
    'corporate.impact.desc': 'Las empresas asociadas a Missionary Medical Care invierten directamente en la creación de infraestructura tecnológica e insumos médicos para áreas del mundo donde la salud es inaccesible. Tu empresa puede alinear sus objetivos de RSE con un impacto humano medible.',
    'corporate.why.title': '¿Por qué asociarse con MMC?',
    'corporate.form.title': 'Inicia una Alianza Corporativa',
    'corporate.form.subtitle': 'Completa el formulario para que nuestro equipo de alianzas estratégicas te contacte.',
    'corporate.form.submit': 'Enviar Propuesta',
    
    'board.hero.title': 'Junta Directiva',
    'board.hero.subtitle': 'Liderazgo comprometido con la excelencia clínica, la seguridad operacional y la misión pactual.',
    'board.team.title': 'Nuestro Liderazgo',
    'board.team.subtitle': 'Un equipo interdisciplinario que guía la visión y garantiza la integridad institucional.',
    
    'health.hero.title': 'Salud Comunitaria y Prevención',
    'health.hero.subtitle': 'Fortaleciendo la resiliencia de las comunidades misioneras mediante educación sanitaria, profilaxis y cuidado preventivo integral.',
    'health.pillars.title': 'Nuestros Pilares de Cuidado',
    'health.pillars.subtitle': 'Implementamos estrategias de salud pública adaptadas a las realidades únicas de los obreros transculturales, promoviendo el bienestar antes de que ocurra la emergencia.',
    'health.p1.title': 'Prevención y Profilaxis',
    'health.p1.desc': 'Asesoramiento en esquemas de vacunación, prevención de enfermedades endémicas y saneamiento básico adaptado al contexto local del misionero.',
    'health.p2.title': 'Salud Materno-Infantil',
    'health.p2.desc': 'Acompañamiento especializado para familias misioneras: cuidado prenatal remoto, asesoría en nutrición infantil y monitoreo de hitos de desarrollo de los TCKs.',
    'health.p3.title': 'Educación Sanitaria',
    'health.p3.desc': 'Capacitación continua en primeros auxilios, purificación de agua, higiene de alimentos y protocolos de bioseguridad para zonas rurales o de alto riesgo.',

    'empty.construction': 'EM CONSTRUÇÃO',
    'empty.desc': 'Esta página estará disponible pronto.',
`;

const newPT = `
    // ==== FASE 3: NUEVAS PAGINAS ====
    'donate.hero.title': 'Invista no Reino',
    'donate.hero.subtitle': 'Com a sua contribuição, você financia telemedicina de emergência e suporte médico criptografado para obreiros na Janela 10/40 e zonas de alta restrição.',
    'donate.freq.once': 'Única Vez',
    'donate.freq.monthly': 'Mensal',
    'donate.btn': 'Doar Agora com MercadoPago',
    
    'volunteer.hero.title': 'Sirva Conosco',
    'volunteer.hero.subtitle': 'Use seus dons médicos e técnicos para sustentar a retaguarda da Grande Comissão.',
    'volunteer.models.title': 'Modelos de Recrutamento',
    'volunteer.models.subtitle': 'Oferecemos opções flexíveis para que você possa se integrar à equipe de acordo com sua disponibilidade e chamado.',
    'volunteer.models.ft.title': 'Full-Time Corps',
    'volunteer.models.ft.desc': 'Compromisso de longo prazo (3+ anos) para médicos de carreira e missionários de saúde que desejam dedicar suas vidas ao cuidado de obreiros transculturais.',
    'volunteer.models.st.title': 'Reserve Corps (Short-Term)',
    'volunteer.models.st.desc': 'Serviço flexível de 2 semanas a 1 ano para cobrir substituições de emergência em hospitais e clínicas de missão em momentos críticos.',
    'volunteer.spec.title': 'Especialidades Prioritárias',
    'volunteer.spec.subtitle': 'Quem são os mais necessitados neste momento?',
    'volunteer.apply': 'Inscreva-se Agora',
    
    'prayer.hero.title': 'Rede de Intercessão',
    'prayer.hero.subtitle': 'Sustentando os braços daqueles que estão na brecha. Sua oração é nossa principal linha de defesa e cuidado.',
    'prayer.impact.title': 'Impacto Global de Oração',
    'prayer.impact.subtitle': 'Pedidos levantados ao Senhor por nossa rede',
    'prayer.btn.prayed': 'Já Orou',
    'prayer.btn.pray': 'Orei por Isso',
    
    'stories.hero.title': 'Histórias e Impacto',
    'stories.hero.subtitle': 'Conheça em primeira mão como o cuidado integral com a saúde está transformando o campo missionário global.',
    'stories.patients.title': 'Histórias de Pacientes',
    'stories.patients.desc': 'Testemunhos de missionários e famílias que receberam assistência médica, psicológica ou de telemedicina em situações críticas. Histórias de graça, resiliência e provisão.',
    'stories.patients.link': 'Ler Testemunhos',
    'stories.reality.title': 'A Realidade do Campo',
    'stories.reality.desc': 'Explore os verdadeiros desafios de saúde, isolamento, logística e segurança (OPSEC) enfrentados pelos obreiros transculturais na Janela 10/40.',
    'stories.reality.link': 'Conhecer a Realidade',
    
    'hub.hero.title': 'Participe e Faça a Diferença',
    'hub.hero.subtitle': 'Existem muitas maneiras de ser a retaguarda da Grande Comissão. Encontre o seu lugar em nossa rede internacional de cuidado.',
    'hub.donate.title': 'Doar',
    'hub.donate.desc': 'Sustente a retaguarda dos missionários financiando cuidados médicos, evacuações e desenvolvimento de telemedicina segura.',
    'hub.volunteer.title': 'Voluntariado',
    'hub.volunteer.desc': 'Use sua profissão (Médicos, Enfermeiros, TI) para fornecer suporte especializado de curto ou longo prazo.',
    'hub.church.title': 'Igrejas Parceiras',
    'hub.church.desc': 'Envolva sua congregação na missão de cuidar dos que foram enviados através de ofertas, oração e conscientização.',
    'hub.prayer.title': 'Rede de Oração',
    'hub.prayer.desc': 'Interceda pelos desafios de saúde física, mental e espiritual enfrentados pelos obreiros nas nações.',
    'hub.link': 'Saiba Mais',
    
    'church.hero.title': 'Igrejas Parceiras',
    'church.hero.subtitle': 'A Igreja Local é a protagonista da Grande Comissão. Nós somos sua retaguarda técnica e médica.',
    'church.axes.title': 'Três Eixos de Colaboração',
    'church.axes.pray.title': 'Oramos',
    'church.axes.pray.desc': 'Conecte sua congregação a motivos reais e confidenciais do campo. Interceda pela saúde e proteção dos obreiros transculturais.',
    'church.axes.give.title': 'Contribuímos',
    'church.axes.give.desc': 'Invistam como igreja na criação de infraestrutura médica resiliente e segura. Cada contribuição patrocina atendimento gratuito para missionários.',
    'church.axes.go.title': 'Vamos',
    'church.axes.go.desc': 'Mobilize os profissionais de saúde de sua igreja para servir a curto ou longo prazo usando seus dons para o Reino.',
    'church.form.title': 'Convide a MMC para sua Igreja',
    'church.form.subtitle': 'Solicite uma apresentação, conferência ou workshop sobre Cuidado Integral e Saúde Missionária.',
    'church.form.submit': 'Enviar Solicitação',
    
    'corporate.hero.title': 'Empresas e Instituições',
    'corporate.hero.subtitle': 'Programa "Partners in Care": Responsabilidade Social Corporativa focada em saúde global de alto risco.',
    'corporate.impact.title': 'Impacto Corporativo Real',
    'corporate.impact.desc': 'Empresas parceiras da Missionary Medical Care investem diretamente na criação de infraestrutura tecnológica e suprimentos médicos para áreas do mundo onde a saúde é inacessível. Sua empresa pode alinhar seus objetivos de RSC com um impacto humano mensurável.',
    'corporate.why.title': 'Por que fazer parceria com a MMC?',
    'corporate.form.title': 'Inicie uma Parceria Corporativa',
    'corporate.form.subtitle': 'Preencha o formulário para que nossa equipe de alianças estratégicas entre em contato.',
    'corporate.form.submit': 'Enviar Proposta',
    
    'board.hero.title': 'Conselho de Administração',
    'board.hero.subtitle': 'Liderança comprometida com a excelência clínica, segurança operacional e a missão pactual.',
    'board.team.title': 'Nossa Liderança',
    'board.team.subtitle': 'Uma equipe interdisciplinar que orienta a visão e garante a integridade institucional.',
    
    'health.hero.title': 'Saúde Comunitária e Prevenção',
    'health.hero.subtitle': 'Fortalecendo a resiliência das comunidades missionárias através de educação em saúde, profilaxia e cuidado preventivo abrangente.',
    'health.pillars.title': 'Nossos Pilares de Cuidado',
    'health.pillars.subtitle': 'Implementamos estratégias de saúde pública adaptadas às realidades únicas dos obreiros transculturais, promovendo o bem-estar antes que a emergência ocorra.',
    'health.p1.title': 'Prevenção e Profilaxia',
    'health.p1.desc': 'Aconselhamento sobre esquemas de vacinação, prevenção de doenças endêmicas e saneamento básico adaptado ao contexto local do missionário.',
    'health.p2.title': 'Saúde Materno-Infantil',
    'health.p2.desc': 'Apoio especializado para famílias missionárias: atendimento pré-natal remoto, aconselhamento nutricional infantil e monitoramento dos marcos de desenvolvimento dos TCKs.',
    'health.p3.title': 'Educação em Saúde',
    'health.p3.desc': 'Treinamento contínuo em primeiros socorros, purificação de água, higiene alimentar e protocolos de biossegurança para áreas rurais ou de alto risco.',

    'empty.construction': 'EM CONSTRUÇÃO',
    'empty.desc': 'Esta página estará disponível em breve.',
`;

const newEN = `
    // ==== FASE 3: NUEVAS PAGINAS ====
    'donate.hero.title': 'Invest in the Kingdom',
    'donate.hero.subtitle': 'With your contribution, you fund emergency telemedicine and encrypted medical support for workers in the 10/40 Window and high-restriction zones.',
    'donate.freq.once': 'One-Time',
    'donate.freq.monthly': 'Monthly',
    'donate.btn': 'Donate Now with MercadoPago',
    
    'volunteer.hero.title': 'Serve With Us',
    'volunteer.hero.subtitle': 'Use your medical and technical gifts to support the rearguard of the Great Commission.',
    'volunteer.models.title': 'Recruitment Models',
    'volunteer.models.subtitle': 'We offer flexible options so you can join the team according to your availability and calling.',
    'volunteer.models.ft.title': 'Full-Time Corps',
    'volunteer.models.ft.desc': 'Long-term commitment (3+ years) for career doctors and health missionaries who want to dedicate their lives to caring for cross-cultural workers.',
    'volunteer.models.st.title': 'Reserve Corps (Short-Term)',
    'volunteer.models.st.desc': 'Flexible service from 2 weeks to 1 year to cover emergency relief in mission hospitals and clinics during critical moments.',
    'volunteer.spec.title': 'Priority Specialties',
    'volunteer.spec.subtitle': 'Who are the most needed right now?',
    'volunteer.apply': 'Apply Now',
    
    'prayer.hero.title': 'Intercession Network',
    'prayer.hero.subtitle': 'Holding up the arms of those standing in the gap. Your prayer is our primary line of defense and care.',
    'prayer.impact.title': 'Global Prayer Impact',
    'prayer.impact.subtitle': 'Requests lifted up to the Lord by our network',
    'prayer.btn.prayed': 'Already Prayed',
    'prayer.btn.pray': 'I Have Prayed for This',
    
    'stories.hero.title': 'Stories and Impact',
    'stories.hero.subtitle': 'Get a first-hand look at how comprehensive healthcare is transforming the global mission field.',
    'stories.patients.title': 'Patient Stories',
    'stories.patients.desc': 'Testimonies of missionaries and families who have received medical, psychological, or telemedicine assistance in critical situations. Stories of grace, resilience, and provision.',
    'stories.patients.link': 'Read Testimonies',
    'stories.reality.title': 'The Reality of the Field',
    'stories.reality.desc': 'Explore the real challenges of health, isolation, logistics, and security (OPSEC) faced by cross-cultural workers in the 10/40 Window.',
    'stories.reality.link': 'Know the Reality',
    
    'hub.hero.title': 'Get Involved and Make a Difference',
    'hub.hero.subtitle': 'There are many ways to be the rearguard of the Great Commission. Find your place in our international network of care.',
    'hub.donate.title': 'Donate',
    'hub.donate.desc': 'Support the rearguard of missionaries by funding medical care, evacuations, and the development of secure telemedicine.',
    'hub.volunteer.title': 'Volunteer',
    'hub.volunteer.desc': 'Use your profession (Doctors, Nurses, IT) to provide specialized short- or long-term support.',
    'hub.church.title': 'Partner Churches',
    'hub.church.desc': 'Engage your congregation in the mission of caring for those who are sent through offerings, prayer, and awareness.',
    'hub.prayer.title': 'Prayer Network',
    'hub.prayer.desc': 'Intercede for the physical, mental, and spiritual health challenges faced by workers in the nations.',
    'hub.link': 'Learn More',
    
    'church.hero.title': 'Partner Churches',
    'church.hero.subtitle': 'The Local Church is the protagonist of the Great Commission. We are its technical and medical rearguard.',
    'church.axes.title': 'Three Axes of Collaboration',
    'church.axes.pray.title': 'We Pray',
    'church.axes.pray.desc': 'Connect your congregation with real and confidential motives from the field. Intercede for the health and protection of cross-cultural workers.',
    'church.axes.give.title': 'We Give',
    'church.axes.give.desc': 'Invest as a church in creating resilient and secure medical infrastructure. Every contribution sponsors free care for missionaries.',
    'church.axes.go.title': 'We Go',
    'church.axes.go.desc': 'Mobilize the health professionals in your church to serve short or long term using their gifts for the Kingdom.',
    'church.form.title': 'Invite MMC to your Church',
    'church.form.subtitle': 'Request a presentation, conference, or workshop on Comprehensive Care and Missionary Health.',
    'church.form.submit': 'Send Request',
    
    'corporate.hero.title': 'Companies and Institutions',
    'corporate.hero.subtitle': '"Partners in Care" Program: Corporate Social Responsibility focused on high-risk global health.',
    'corporate.impact.title': 'Real Corporate Impact',
    'corporate.impact.desc': 'Companies partnering with Missionary Medical Care invest directly in creating technological infrastructure and medical supplies for areas of the world where healthcare is inaccessible. Your company can align its CSR goals with measurable human impact.',
    'corporate.why.title': 'Why partner with MMC?',
    'corporate.form.title': 'Start a Corporate Partnership',
    'corporate.form.subtitle': 'Fill out the form so our strategic alliances team can contact you.',
    'corporate.form.submit': 'Send Proposal',
    
    'board.hero.title': 'Board of Directors',
    'board.hero.subtitle': 'Leadership committed to clinical excellence, operational security, and the covenantal mission.',
    'board.team.title': 'Our Leadership',
    'board.team.subtitle': 'An interdisciplinary team that guides the vision and guarantees institutional integrity.',
    
    'health.hero.title': 'Community Health and Prevention',
    'health.hero.subtitle': 'Strengthening the resilience of missionary communities through health education, prophylaxis, and comprehensive preventive care.',
    'health.pillars.title': 'Our Pillars of Care',
    'health.pillars.subtitle': 'We implement public health strategies adapted to the unique realities of cross-cultural workers, promoting well-being before an emergency occurs.',
    'health.p1.title': 'Prevention and Prophylaxis',
    'health.p1.desc': 'Advice on vaccination schedules, prevention of endemic diseases, and basic sanitation adapted to the missionary\\'s local context.',
    'health.p2.title': 'Maternal and Child Health',
    'health.p2.desc': 'Specialized support for missionary families: remote prenatal care, infant nutrition counseling, and monitoring of TCK development milestones.',
    'health.p3.title': 'Health Education',
    'health.p3.desc': 'Continuous training in first aid, water purification, food hygiene, and biosecurity protocols for rural or high-risk areas.',

    'empty.construction': 'UNDER CONSTRUCTION',
    'empty.desc': 'This page will be available soon.',
`;

// Find the start of PT block
content = content.replace(/\\s*PT:\\s*\\{/, ',' + newES + '\\n  },\n  PT: {');
// Find the start of EN block
content = content.replace(/\\s*EN:\\s*\\{/, ',' + newPT + '\\n  },\n  EN: {');
// Find the end of EN block (last brace)
content = content.replace(/\\s*\\}\\s*\\};\\s*$/, ',' + newEN + '\\n  }\n};');

fs.writeFileSync('src/context/LanguageContext.tsx', content);
