import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'ES' | 'PT' | 'EN';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ES: {
    'nav.who': 'Quién soy',
    'nav.what': 'Qué hago',
    'nav.contact': 'Contacto',
    'nav.title': 'Dr. Samuel Silva',
    'nav.subtitle': 'Médico · Investigador · Salud Global · Bioética · Inteligencia Artificial',
    'nav.home': 'Inicio',
    'nav.about': 'Sobre mí',
    'nav.trajectory': 'Mi Trayectoria',
    'nav.academic': 'Trayectoria Académica',
    'nav.articles': 'Artículos',
    'nav.podcast': 'Podcast',
    'nav.gcn': 'Global Care Network',
    'footer.rights': 'Todos los derechos reservados.',
    'nav.back': 'Volver al inicio',
    'gcn.nav.home': 'Inicio',
    'gcn.nav.about': 'Sobre GCN',
    'gcn.nav.projects': 'Proyectos',
    'gcn.nav.telemedicine': 'Telemedicina',
    'gcn.nav.digitalHealth': 'Salud Digital',
    'gcn.nav.resources': 'Recursos',
    'gcn.nav.founder': 'Liderazgo',
    'gcn.hero.title': 'Iniciativa Independiente de Investigación en Salud Digital',
    'gcn.hero.subtitle': 'Investigamos, desarrollamos y validamos soluciones prácticas en telemedicina, salud digital e inteligencia artificial clínica para responder a desafíos reales de la atención sanitaria en entornos con recursos limitados.',
    'gcn.hero.explore': 'Ver Proyectos',
    'gcn.hero.learn': 'Conocer GCN',
    'gcn.about.title': 'Sobre Global Care Network',
    'gcn.about.subtitle': 'Comenzar con humildad. Construir con excelencia. Crecer con credibilidad.',
    'gcn.about.p1': 'Global Care Network (GCN) es una iniciativa independiente de investigación centrada en el desarrollo, evaluación y validación de tecnologías aplicadas a la salud digital.',
    'gcn.about.p2': 'Nuestra investigación integra telemedicina, inteligencia artificial clínica, tecnologías de diagnóstico remoto y modelos de atención para entornos con recursos limitados, siempre bajo principios de evidencia científica, ética médica y seguridad.',
    'gcn.about.p3': 'Todos los proyectos de GCN se desarrollan de forma progresiva mediante investigación aplicada, validación clínica y evaluación operativa antes de su implementación.',
    'gcn.reason.title': '¿Por qué existe Global Care Network?',
    'gcn.reason.p1': 'Global Care Network (GCN) es una iniciativa independiente de investigación dedicada al estudio, desarrollo y validación de soluciones prácticas para mejorar el acceso a la atención médica en comunidades con recursos limitados.',
    'gcn.reason.p2': 'Nuestro trabajo parte de problemas clínicos observados durante años de práctica médica en terreno. En lugar de desarrollar tecnología por sí misma, investigamos herramientas que respondan a necesidades reales, siempre desde una perspectiva ética, basada en evidencia y orientada al beneficio del paciente.',
    'gcn.reason.p3': 'Actualmente desarrollamos proyectos piloto y evaluamos nuevas tecnologías antes de su implementación a mayor escala.',
    'gcn.about.approach.title': 'Nuestro Enfoque',
    'gcn.about.approach.desc': 'GCN desarrolla soluciones de salud basadas en la investigación aplicada e inspiradas en necesidades clínicas reales. Diseñamos herramientas para apoyar la práctica médica y mejorar de manera responsable y segura la atención al paciente.',
    'gcn.about.work.title': 'Cómo Trabajamos',
    'gcn.about.work.step1': 'Necesidad Clínica Real',
    'gcn.about.work.step2': 'Revisión de la Evidencia',
    'gcn.about.work.step3': 'Diseño de la Solución',
    'gcn.about.work.step4': 'Piloto en el Terreno',
    'gcn.about.work.step5': 'Evaluación Clínica',
    'gcn.about.work.step6': 'Mejora Continua',
    'gcn.about.principles.title': 'Nuestros Principios Guía',
    'gcn.about.principles.patient.title': 'Cuidado Centrado en el Paciente',
    'gcn.about.principles.patient.desc': 'El paciente y su dignidad humana son la prioridad absoluta. La tecnología es solo una herramienta de soporte al cuidado clínico.',
    'gcn.about.principles.evidence.title': 'Medicina Basada en Evidencia',
    'gcn.about.principles.evidence.desc': 'Todas las recomendaciones, proyectos y soluciones desarrolladas por GCN se fundamentan en la mejor evidencia científica disponible y en la práctica clínica responsable.',
    'gcn.about.principles.innovation.title': 'Innovación Práctica',
    'gcn.about.principles.innovation.desc': 'La tecnología existe para resolver problemas reales en el cuidado del paciente, no para generar impacto comercial.',
    'gcn.about.principles.transparency.title': 'Transparencia',
    'gcn.about.principles.transparency.desc': 'Presentamos con honestidad el estado real de cada proyecto y las limitaciones reales de la tecnología médica actual.',
    'gcn.about.principles.professionalism.title': 'Profesionalismo',
    'gcn.about.principles.professionalism.desc': 'Mantenemos un rigor clínico y científico estricto, basándonos siempre en la medicina fundamentada en la evidencia.',
    'gcn.projects.title': 'Nuestros Proyectos',
    'gcn.projects.subtitle': 'Iniciativas y herramientas de salud digital en desarrollo.',
    'gcn.projects.p1': 'Presentamos con transparencia el estado actual de nuestras iniciativas. Cada proyecto responde a una necesidad clínica real observada en el terreno.',
    'gcn.projects.headers.problem': 'Problema Clínico',
    'gcn.projects.headers.solution': 'Solución Propuesta',
    'gcn.projects.headers.stage': 'Estado Actual',
    'gcn.projects.headers.next': 'Próximo Paso',
    'gcn.projects.headers.impact': 'Impacto Esperado',
    'gcn.projects.p1.title': 'Telemedicina para Entornos Remotos',
    'gcn.projects.p1.problem': 'Los profesionales de la salud que trabajan en comunidades rurales y remotas a menudo tienen acceso limitado a médicos, especialistas y servicios de diagnóstico. Esto puede retrasar el diagnóstico, interrumpir la continuidad de la atención y requerir traslados innecesarios de pacientes.',
    'gcn.projects.p1.solution': 'Desarrollar un modelo de telemedicina práctico que apoye las consultas remotas, el teletriage y la colaboración clínica utilizando tecnologías accesibles adaptadas a entornos con recursos limitados.',
    'gcn.projects.p1.status': 'Piloto',
    'gcn.projects.p1.next': 'Estandarizar protocolos de telemedicina, mejorar la documentación clínica y expandir gradualmente la implementación a entornos remotos adicionales.',
    'gcn.projects.p1.impact': '• Facilitar el acceso oportuno a orientación médica.\n• Reducir traslados innecesarios.\n• Mejorar la continuidad de la atención.\n• Fortalecer el apoyo clínico en comunidades remotas.',
    'gcn.projects.p2.title': 'Kit de Telemedicina Portátil',
    'gcn.projects.p2.problem': 'Los equipos de salud móviles que trabajan en comunidades aisladas con frecuencia carecen de equipos de diagnóstico esenciales y de una infraestructura eléctrica confiable, lo que limita su capacidad para realizar evaluaciones clínicas oportunas.',
    'gcn.projects.p2.solution': 'Desarrollar un kit de telemedicina portátil que integre dispositivos médicos esenciales, suministro de energía autónomo y tecnologías de comunicación para apoyar la prestación de servicios de salud en entornos remotos.',
    'gcn.projects.p2.status': 'Planificación & Desarrollo',
    'gcn.projects.p2.next': 'Construir el primer prototipo funcional y realizar evaluaciones de campo para valorar la usabilidad clínica, portabilidad y viabilidad operativa.',
    'gcn.projects.p2.impact': '• Incrementar la capacidad diagnóstica en terreno.\n• Facilitar la atención médica fuera de hospitales.\n• Mejorar la autonomía de equipos móviles.',
    'gcn.projects.p3.title': 'Soporte Clínico con IA Responsable',
    'gcn.projects.p3.problem': 'Los profesionales de atención primaria de salud a menudo toman decisiones clínicas complejas con recursos de diagnóstico limitados y acceso restringido al apoyo de especialistas. Las herramientas de IA existentes no siempre están diseñadas para estas realidades.',
    'gcn.projects.p3.solution': 'Evaluar e implementar herramientas de inteligencia artificial responsable que apoyen el razonamiento clínico, la educación médica y los flujos de trabajo de atención médica, manteniendo al mismo tiempo una supervisión humana continua y una práctica basada en la evidencia.',
    'gcn.projects.p3.status': 'Concepto & Desarrollo',
    'gcn.projects.p3.next': 'Evaluar las plataformas de IA clínica disponibles, definir flujos de trabajo de buenas prácticas y desarrollar directrices para la integración segura y responsable de la IA en la atención primaria de salud y la telemedicina.',
    'gcn.projects.p3.impact': '• Apoyar el razonamiento clínico.\n• Facilitar el acceso a información basada en evidencia.\n• Promover el uso responsable de IA en atención primaria.\n• Mantener siempre la supervisión humana.',
    'gcn.resources.title': 'Recursos',
    'gcn.resources.subtitle': 'Herramientas, guías y recursos de salud digital para profesionales del terreno.',
    'gcn.resources.p1': 'Espacio dedicado a compartir protocolos de atención y material de formación.',
    'gcn.resources.item1.title': 'Protocolos Clínicos',
    'gcn.resources.item1.desc': 'Estándares clínicos de soporte adaptados a la telemedicina y el teletriage rural.',
    'gcn.resources.item2.title': 'Guías Prácticas',
    'gcn.resources.item2.desc': 'Manuales para la implementación de equipos de telesalud independientes.',
    'gcn.resources.item3.title': 'Herramientas Digitales',
    'gcn.resources.item3.desc': 'Recursos y plantillas de código abierto de GCN para flujos de trabajo de información.',
    'gcn.resources.item4.title': 'Artículos y Evidencia',
    'gcn.resources.item4.desc': 'Recopilación de estudios científicos sobre medicina basada en evidencia.',
    'gcn.resources.item5.title': 'Material Educativo',
    'gcn.resources.item5.desc': 'Material didáctico para promotores y personal de atención médica comunitaria.',
    'gcn.resources.item6.title': 'Recursos para Telemedicina',
    'gcn.resources.item6.desc': 'Configuraciones y especificaciones técnicas para entornos de baja conectividad.',
    'gcn.founder.title': 'Liderazgo',
    'gcn.founder.name': 'Dr. Samuel Silva',
    'gcn.founder.role': 'Fundador · Director Médico · Investigador en Salud Digital',
    'gcn.founder.tagline': 'Investigación Clínica • Telemedicina • Salud Digital • Inteligencia Artificial Clínica',
    'gcn.founder.bio': 'Dr. Samuel Silva es médico general con experiencia en atención primaria, medicina comunitaria y telemedicina en entornos con recursos limitados. Durante más de catorce años ha trabajado en comunidades rurales, desarrollando soluciones para mejorar el acceso a la atención médica donde los recursos especializados son escasos. Su experiencia clínica motivó la creación de Global Care Network como una iniciativa independiente de investigación dedicada al estudio, desarrollo y validación de tecnologías aplicadas a la telemedicina, la salud digital y la inteligencia artificial clínica.',
    'gcn.founder.about': 'Sobre el Director Médico',
    'gcn.founder.why.title': '¿Por qué existe Global Care Network?',
    'gcn.founder.why.p1': 'Global Care Network nació a partir de la práctica clínica durante años en comunidades rurales y entornos con recursos limitados, donde el acceso a la salud suele verse dificultado por la distancia y la falta de soporte especializado.',
    'gcn.founder.why.p2': 'En lugar de crear tecnología por sí misma, GCN desarrolla soluciones prácticas basadas en la investigación aplicada que responden a necesidades clínicas reales observadas en el ejercicio cotidiano de la medicina.',
    'gcn.founder.interests': 'Intereses Profesionales',
    'gcn.founder.i1': 'Atención Primaria de Salud',
    'gcn.founder.i2': 'Envejecimiento Saludable',
    'gcn.founder.i3': 'Telemedicina & Salud Digital',
    'gcn.founder.i4': 'Inteligencia Artificial Clínica',
    'gcn.founder.i5': 'Medicina Rural y Comunitaria',
    'gcn.founder.i6': 'Salud Global',
    'gcn.founder.i7': 'Medicina Basada en Evidencias',
    'gcn.telemed.p1': 'Facilitamos el soporte médico a distancia y la interconsulta para profesionales de salud en áreas rurales y de difícil acceso mediante herramientas asíncronas optimizadas para baja conectividad.',
    'gcn.ai.p1': 'Investigamos el uso responsable de la Inteligencia Artificial Clínica como soporte en el triage y la toma de decisiones clínicas primarias, manteniendo siempre la supervisión médica humana como eje insustituible.',
    'gcn.partners.p1': 'Colaboramos activamente con universidades, redes médicas y profesionales de salud interesados en la validación clínica y científica de herramientas de telemedicina.',
  },
  PT: {
    'nav.who': 'Quem sou',
    'nav.what': 'O que faço',
    'nav.contact': 'Contato',
    'nav.title': 'Dr. Samuel Silva',
    'nav.subtitle': 'Médico · Pesquisador · Saúde Global · Bioética · Inteligência Artificial',
    'nav.home': 'Início',
    'nav.about': 'Sobre mim',
    'nav.trajectory': 'Minha Trajetória',
    'nav.academic': 'Trajetória Acadêmica',
    'nav.articles': 'Artigos',
    'nav.podcast': 'Podcast',
    'nav.gcn': 'Global Care Network',
    'footer.rights': 'Todos os direitos reservados.',
    'nav.back': 'Voltar ao Início',
    'gcn.nav.home': 'Início',
    'gcn.nav.about': 'Sobre a GCN',
    'gcn.nav.projects': 'Projetos',
    'gcn.nav.telemedicine': 'Telemedicina',
    'gcn.nav.digitalHealth': 'Saúde Digital',
    'gcn.nav.resources': 'Recursos',
    'gcn.nav.founder': 'Liderança',
    'gcn.hero.title': 'Iniciativa Independente de Pesquisa em Saúde Digital',
    'gcn.hero.subtitle': 'Pesquisamos, desenvolvemos e validamos soluções práticas em telemedicina, saúde digital e inteligência artificial clínica para responder a desafios reais da atenção à saúde em ambientes com recursos limitados.',
    'gcn.hero.explore': 'Ver Projetos',
    'gcn.hero.learn': 'Conhecer GCN',
    'gcn.about.title': 'Sobre a Global Care Network',
    'gcn.about.subtitle': 'Começar com humildade. Construir com excelência. Crescer com credibilidade.',
    'gcn.about.p1': 'A Global Care Network (GCN) é uma iniciativa independente de pesquisa centrada no desenvolvimento, avaliação e validação de tecnologias aplicadas à saúde digital.',
    'gcn.about.p2': 'Nossa pesquisa integra telemedicina, inteligência artificial clínica, tecnologias de diagnóstico remoto e modelos de atendimento para ambientes com recursos limitados, sempre sob princípios de evidência científica, ética médica e segurança.',
    'gcn.about.p3': 'Todos os projetos da GCN desenvolvem-se de forma progressiva mediante pesquisa aplicada, validação clínica e avaliação operacional antes de sua implementação.',
    'gcn.reason.title': 'Por que existe a Global Care Network?',
    'gcn.reason.p1': 'A Global Care Network (GCN) é uma iniciativa independente de pesquisa dedicada ao estudo, desenvolvimento e validação de soluções práticas para melhorar o acesso à atenção médica em comunidades com recursos limitados.',
    'gcn.reason.p2': 'Nosso trabalho parte de problemas clínicos observados durante anos de prática médica em campo. Em vez de desenvolver tecnologia por si só, pesquisamos ferramentas que respondam a necessidades reais, sempre sob uma perspectiva ética, baseada em evidências e orientada ao benefício do paciente.',
    'gcn.reason.p3': 'Atualmente, desenvolvemos projetos-piloto e avaliamos novas tecnologias antes de sua implementação em maior escala.',
    'gcn.about.approach.title': 'Nossa Abordagem',
    'gcn.about.approach.desc': 'A GCN desenvolve soluções de saúde baseadas em pesquisa aplicada e inspiradas em necessidades clínicas reais. Projetamos ferramentas para apoiar a prática médica e melhorar de forma responsável e segura a atenção ao paciente.',
    'gcn.about.work.title': 'Como Trabalhamos',
    'gcn.about.work.step1': 'Necessidade Clínica Real',
    'gcn.about.work.step2': 'Revisão da Evidência',
    'gcn.about.work.step3': 'Design da Solução',
    'gcn.about.work.step4': 'Piloto em Campo',
    'gcn.about.work.step5': 'Avaliação Clínica',
    'gcn.about.work.step6': 'Melhoria Contínua',
    'gcn.about.principles.title': 'Nossos Princípios Orientadores',
    'gcn.about.principles.patient.title': 'Cuidado Centrado no Paciente',
    'gcn.about.principles.patient.desc': 'O paciente e sua dignidade humana são a prioridade absoluta. A tecnologia é apenas uma ferramenta de suporte ao cuidado clínico.',
    'gcn.about.principles.evidence.title': 'Medicina Baseada em Evidência',
    'gcn.about.principles.evidence.desc': 'Todas as recomendações, projetos e soluções desenvolvidas pela GCN fundamentam-se na melhor evidência científica disponível e na prática clínica responsável.',
    'gcn.about.principles.innovation.title': 'Inovação Prática',
    'gcn.about.principles.innovation.desc': 'A tecnologia existe para resolver problemas reais no cuidado do paciente, não para gerar impacto comercial.',
    'gcn.about.principles.transparency.title': 'Transparência',
    'gcn.about.principles.transparency.desc': 'Apresentamos com honestidade o estado real de cada projeto e as limitações reais da tecnologia médica atual.',
    'gcn.about.principles.professionalism.title': 'Profissionalismo',
    'gcn.about.principles.professionalism.desc': 'Mantemos um rigor clínico e científico estrito, baseando-nos sempre na medicina baseada em evidências.',
    'gcn.projects.title': 'Nossos Projetos',
    'gcn.projects.subtitle': 'Iniciativas e ferramentas de saúde digital em desenvolvimento.',
    'gcn.projects.p1': 'Apresentamos com transparência o estado atual das nossas iniciativas. Cada projeto responde a uma necessidade clínica real observada no campo.',
    'gcn.projects.headers.problem': 'Problema Clínico',
    'gcn.projects.headers.solution': 'Solução Proposta',
    'gcn.projects.headers.stage': 'Estado Atual',
    'gcn.projects.headers.next': 'Próximo Passo',
    'gcn.projects.headers.impact': 'Impacto Esperado',
    'gcn.projects.p1.title': 'Telemedicina para Contextos Remotos',
    'gcn.projects.p1.problem': 'Os profissionais de saúde que atuam em comunidades rurais e isoladas frequentemente possuem acesso limitado a médicos, especialistas e serviços de diagnóstico. Isso pode atrasar o diagnóstico, interromper a continuidade da assistência e exigir transferências desnecessárias de pacientes.',
    'gcn.projects.p1.solution': 'Desenvolver um modelo prático de telemedicina que apoie consultas remotas, teletriagem e colaboração clínica utilizando tecnologias acessíveis e adaptadas a ambientes com recursos limitados.',
    'gcn.projects.p1.status': 'Piloto',
    'gcn.projects.p1.next': 'Padronizar protocolos de telemedicina, aprimorar a documentação clínica e expandir gradualmente a implementação para contextos remotos adicionais.',
    'gcn.projects.p1.impact': '• Facilitar o acesso oportuno a orientação médica.\n• Reduzir traslados desnecessários.\n• Melhorar a continuidade da assistência.\n• Fortalecer o apoio clínico em comunidades remotas.',
    'gcn.projects.p2.title': 'Kit de Telemedicina Portátil',
    'gcn.projects.p2.problem': 'Equipes móveis de saúde que atuam em comunidades isoladas frequentemente carecem de equipamentos de diagnóstico essenciais e de infraestrutura elétrica confiável, limitando sua capacidade de realizar avaliações clínicas oportunas.',
    'gcn.projects.p2.solution': 'Desenvolver um kit de telemedicina portátil que integre dispositivos médicos essenciais, fornecimento autônomo de energia e tecnologias de comunicação para apoiar a prestação de serviços de saúde em ambientes remotos.',
    'gcn.projects.p2.status': 'Planejamento & Desenvolvimento',
    'gcn.projects.p2.next': 'Construir o primeiro protótipo funcional e realizar avaliações de campo para mensurar a usabilidade clínica, portabilidade e viabilidade operacional.',
    'gcn.projects.p2.impact': '• Incrementar a capacidade diagnóstica em terreno.\n• Facilitar a atenção médica fora de hospitais.\n• Melhorar a autonomia de equipes móveis.',
    'gcn.projects.p3.title': 'Suporte Clínico com IA Responsável',
    'gcn.projects.p3.problem': 'Profissionais da atenção primária à saúde frequentemente tomam decisões clínicas complexas com recursos de diagnóstico limitados e acesso restrito a suporte especializado. As ferramentas de IA existentes nem sempre são projetadas para essa realidade.',
    'gcn.projects.p3.solution': 'Avaliar e implementar ferramentas de inteligência artificial responsável que auxiliem no raciocínio clínico, na educação médica e nos fluxos de trabalho de saúde, mantendo simultaneamente a supervisão humana contínua e a prática baseada em evidências.',
    'gcn.projects.p3.status': 'Conceito & Desenvolvimento',
    'gcn.projects.p3.next': 'Avaliar as plataformas de IA clínica disponíveis, definir fluxos de trabalho de boas práticas e desenvolver diretrizes para a integração segura e responsável da IA na atenção primária à saúde e telemedicina.',
    'gcn.projects.p3.impact': '• Apoiar o raciocínio clínico.\n• Facilitar o acesso a informações baseadas em evidências.\n• Promover o uso responsável da IA na atenção primária.\n• Manter sempre a supervisão humana.',
    'gcn.resources.title': 'Recursos',
    'gcn.resources.subtitle': 'Ferramentas, guias e recursos de saúde digital para profissionais do campo.',
    'gcn.resources.p1': 'Espaço dedicado ao compartilhamento de produtos e materiais de treinamento.',
    'gcn.resources.item1.title': 'Protocolos Clínicos',
    'gcn.resources.item1.desc': 'Padrões clínicos de suporte adaptados à telemedicina e teletriagem rural.',
    'gcn.resources.item2.title': 'Guias Prácticas',
    'gcn.resources.item2.desc': 'Manuais para a implementação de equipes de telessaúde independentes.',
    'gcn.resources.item3.title': 'Ferramentas Digitais',
    'gcn.resources.item3.desc': 'Recursos e modelos de código aberto da GCN para fluxos de trabalho de informação.',
    'gcn.resources.item4.title': 'Artigos e Evidência',
    'gcn.resources.item4.desc': 'Coletânea de estudos científicos sobre medicina baseada em evidências.',
    'gcn.resources.item5.title': 'Material Educativo',
    'gcn.resources.item5.desc': 'Materiais didáticos para promotores e equipes de saúde comunitária.',
    'gcn.resources.item6.title': 'Recursos para Telemedicina',
    'gcn.resources.item6.desc': 'Configurações e especificações técnicas para ambientes de baixa conectividade.',
    'gcn.founder.title': 'Liderança',
    'gcn.founder.name': 'Dr. Samuel Silva',
    'gcn.founder.role': 'Fundador · Diretor Médico · Pesquisador em Saúde Digital',
    'gcn.founder.tagline': 'Pesquisa Clínica • Telemedicina • Saúde Digital • Inteligência Artificial Clínica',
    'gcn.founder.bio': 'Dr. Samuel Silva é médico geral com experiência em atenção primária, medicina comunitária e telemedicina em ambientes com recursos limitados. Ao longo de mais de catorze anos trabalhando em comunidades rurais, tem desenvolvido soluções para melhorar o acesso à atenção médica onde os recursos especializados são escassos. Sua experiência clínica motivou a criação da Global Care Network como uma iniciativa independente de pesquisa dedicada ao estudo, desenvolvimento e validação de tecnologias aplicadas à telemedicina, saúde digital e inteligência artificial clínica.',
    'gcn.founder.about': 'Sobre o Diretor Médico',
    'gcn.founder.why.title': 'Por que existe a Global Care Network?',
    'gcn.founder.why.p1': 'A Global Care Network nasceu a partir da prática clínica durante anos em comunidades rurais e ambientes com recursos limitados, onde o acesso à saúde costuma ser dificultado pela distância e pela falta de suporte especializado.',
    'gcn.founder.why.p2': 'Em vez de criar tecnologia por si só, a GCN desenvolve soluções práticas baseadas em pesquisa aplicada que respondem a necessidades clínicas reais observadas no exercício cotidiano da medicina.',
    'gcn.founder.interests': 'Interesses Profissionais',
    'gcn.founder.i1': 'Atenção Primária à Saúde',
    'gcn.founder.i2': 'Envelhecimento Saudável',
    'gcn.founder.i3': 'Telemedicina & Saúde Digital',
    'gcn.founder.i4': 'Inteligência Artificial Clínica',
    'gcn.founder.i5': 'Medicina Rural e Comunitária',
    'gcn.founder.i6': 'Saúde Global',
    'gcn.founder.i7': 'Medicina Baseada em Evidências',
    'gcn.telemed.p1': 'Facilitamos o suporte médico à distância e a interconsulta para profissionais de saúde em áreas rurais e de difícil acesso por meio de ferramentas assíncronas otimizadas para baixa conectividade.',
    'gcn.ai.p1': 'Pesquisamos o uso responsável da Inteligência Artificial Clínica como suporte na triagem e tomada de decisões clínicas primárias, mantendo sempre a supervisão médica humana como eixo insubstituível.',
    'gcn.partners.p1': 'Colaboramos ativamente com universidades, redes médicas e profissionais de saúde interessados na validação clínica e científica de ferramentas de telemedicina.',
  },
  EN: {
    'nav.who': 'Who I am',
    'nav.what': 'What I do',
    'nav.contact': 'Contact',
    'nav.title': 'Dr. Samuel Silva',
    'nav.subtitle': 'Physician · Researcher · Global Health · Bioethics · Artificial Intelligence',
    'nav.home': 'Home',
    'nav.about': 'About me',
    'nav.trajectory': 'My Trajectory',
    'nav.academic': 'Academic Trajectory',
    'nav.articles': 'Articles',
    'nav.podcast': 'Podcast',
    'nav.gcn': 'Global Care Network',
    'footer.rights': 'All rights reserved.',
    'nav.back': 'Back to Home',
    'gcn.nav.home': 'Home',
    'gcn.nav.about': 'About GCN',
    'gcn.nav.projects': 'Projects',
    'gcn.nav.telemedicine': 'Telemedicine',
    'gcn.nav.digitalHealth': 'Digital Health',
    'gcn.nav.resources': 'Resources',
    'gcn.nav.founder': 'Leadership',
    'gcn.hero.title': 'Independent Digital Health Research Initiative',
    'gcn.hero.subtitle': 'We research, develop, and validate practical telemedicine, digital health, and clinical artificial intelligence solutions to address real healthcare challenges in resource-limited settings.',
    'gcn.hero.explore': 'View Projects',
    'gcn.hero.learn': 'About GCN',
    'gcn.about.title': 'About Global Care Network',
    'gcn.about.subtitle': 'Start with humility. Build with excellence. Grow with credibility.',
    'gcn.about.p1': 'Global Care Network (GCN) is an independent research initiative focused on the development, evaluation, and validation of technologies applied to digital health.',
    'gcn.about.p2': 'Our research integrates telemedicine, clinical artificial intelligence, remote diagnostic technologies, and healthcare delivery models for resource-limited settings, always guided by scientific evidence, medical ethics, and patient safety.',
    'gcn.about.p3': 'All GCN projects are developed progressively through applied research, clinical validation, and operational evaluation before implementation.',
    'gcn.reason.title': 'Why Global Care Network Exists',
    'gcn.reason.p1': 'Global Care Network (GCN) is an independent research initiative dedicated to the study, development, and validation of practical solutions to improve access to healthcare in resource-limited settings.',
    'gcn.reason.p2': 'Our work stems from clinical problems observed during years of field medical practice. Rather than developing technology for its own sake, we research tools that respond to real needs, always from an ethical, evidence-based, and patient-centered perspective.',
    'gcn.reason.p3': 'Currently, we develop pilot projects and evaluate new technologies before large-scale implementation.',
    'gcn.about.approach.title': 'Our Approach',
    'gcn.about.approach.desc': 'GCN develops health solutions based on applied research and inspired by real clinical needs. We design tools to support medical practice and responsibly and safely improve patient care.',
    'gcn.about.work.title': 'How We Work',
    'gcn.about.work.step1': 'Real Clinical Need',
    'gcn.about.work.step2': 'Evidence Review',
    'gcn.about.work.step3': 'Solution Design',
    'gcn.about.work.step4': 'Field Pilot',
    'gcn.about.work.step5': 'Clinical Evaluation',
    'gcn.about.work.step6': 'Continuous Improvement',
    'gcn.about.principles.title': 'Our Guiding Principles',
    'gcn.about.principles.patient.title': 'Patient-Centered Care',
    'gcn.about.principles.patient.desc': 'The patient and their human dignity are the absolute priority. Technology is only a supporting tool for clinical care.',
    'gcn.about.principles.evidence.title': 'Evidence-Based Medicine',
    'gcn.about.principles.evidence.desc': 'All recommendations, projects, and solutions developed by GCN are grounded in the best available scientific evidence and responsible clinical practice.',
    'gcn.about.principles.innovation.title': 'Practical Innovation',
    'gcn.about.principles.innovation.desc': 'Technology exists to solve real problems in patient care, not to generate commercial impact.',
    'gcn.about.principles.transparency.title': 'Transparency',
    'gcn.about.principles.transparency.desc': 'We honestly present the real status of each project and the real limitations of current medical technology.',
    'gcn.about.principles.professionalism.title': 'Professionalism',
    'gcn.about.principles.professionalism.desc': 'We maintain strict clinical and scientific rigor, always aligning with evidence-based medicine.',
    'gcn.projects.title': 'Our Projects',
    'gcn.projects.subtitle': 'Digital health initiatives and tools currently in development.',
    'gcn.projects.p1': 'We transparently present the current status of our initiatives. Each project addresses a real clinical need observed in the field.',
    'gcn.projects.headers.problem': 'Clinical Problem',
    'gcn.projects.headers.solution': 'Proposed Solution',
    'gcn.projects.headers.stage': 'Current Stage',
    'gcn.projects.headers.next': 'Next Step',
    'gcn.projects.headers.impact': 'Expected Impact',
    'gcn.projects.p1.title': 'Telemedicine for Remote Settings',
    'gcn.projects.p1.problem': 'Healthcare professionals working in rural and remote communities often have limited access to physicians, specialists, and diagnostic services. This can delay diagnosis, interrupt continuity of care, and require unnecessary patient transfers.',
    'gcn.projects.p1.solution': 'Develop a practical telemedicine model that supports remote consultations, teletriage, and clinical collaboration using accessible technologies adapted to resource-limited environments.',
    'gcn.projects.p1.status': 'Pilot',
    'gcn.projects.p1.next': 'Standardize telemedicine protocols, improve clinical documentation, and gradually expand implementation to additional remote settings.',
    'gcn.projects.p1.impact': '• Facilitate timely access to medical guidance.\n• Reduce unnecessary patient transfers.\n• Improve continuity of care.\n• Strengthen clinical support in remote communities.',
    'gcn.projects.p2.title': 'Portable Telemedicine Kit',
    'gcn.projects.p2.problem': 'Mobile healthcare teams working in isolated communities frequently lack essential diagnostic equipment and reliable electrical infrastructure, limiting their ability to perform timely clinical assessments.',
    'gcn.projects.p2.solution': 'Develop a portable telemedicine kit integrating essential medical devices, autonomous power supply, and communication technologies to support healthcare delivery in remote environments.',
    'gcn.projects.p2.status': 'Planning & Development',
    'gcn.projects.p2.next': 'Build the first functional prototype and conduct field evaluations to assess clinical usability, portability, and operational feasibility.',
    'gcn.projects.p2.impact': '• Increase rapid diagnostic capacity in the field.\n• Enable healthcare delivery outside clinical structures.\n• Improve mobile team autonomy.',
    'gcn.projects.p3.title': 'Responsible Clinical AI Support',
    'gcn.projects.p3.problem': 'Primary healthcare professionals often make complex clinical decisions with limited diagnostic resources and restricted access to specialist support. Existing AI tools are not always designed for these realities.',
    'gcn.projects.p3.solution': 'Evaluate and implement responsible artificial intelligence tools that support clinical reasoning, medical education, and healthcare workflows while maintaining continuous human supervision and evidence-based practice.',
    'gcn.projects.p3.status': 'Concept & Development',
    'gcn.projects.p3.next': 'Evaluate available clinical AI platforms, define best-practice workflows, and develop guidance for the safe and responsible integration of AI into primary healthcare and telemedicine.',
    'gcn.projects.p3.impact': '• Support clinical reasoning.\n• Facilitate access to evidence-based medical databases.\n• Promote the responsible use of AI in primary care.\n• Always maintain human medical supervision.',
    'gcn.resources.title': 'Resources',
    'gcn.resources.subtitle': 'Digital health tools, guidelines, and assets for field professionals.',
    'gcn.resources.p1': 'Space dedicated to sharing protocols and clinical educational resources.',
    'gcn.resources.item1.title': 'Clinical Protocols',
    'gcn.resources.item1.desc': 'Clinical standard supports customized for telehealth and remote triage.',
    'gcn.resources.item2.title': 'Practical Guidelines',
    'gcn.resources.item2.desc': 'Manuals for setting up and deploying independent telehealth teams.',
    'gcn.resources.item3.title': 'Digital Tools',
    'gcn.resources.item3.desc': 'GCN-curated resources and open templates for health workflow support.',
    'gcn.resources.item4.title': 'Articles and Evidence',
    'gcn.resources.item4.desc': 'Collected literature on evidence-based health technology.',
    'gcn.resources.item5.title': 'Educational Assets',
    'gcn.resources.item5.desc': 'Guides and materials for community healthcare training.',
    'gcn.resources.item6.title': 'Telemedicine Technical specs',
    'gcn.resources.item6.desc': 'Hardware and connectivity profiles adapted for remote low-bandwidth clinics.',
    'gcn.founder.title': 'Leadership',
    'gcn.founder.name': 'Dr. Samuel Silva',
    'gcn.founder.role': 'Founder · Medical Director · Digital Health Researcher',
    'gcn.founder.tagline': 'Clinical Research • Telemedicine • Digital Health • Clinical Artificial Intelligence',
    'gcn.founder.bio': 'Dr. Samuel Silva is a general physician with experience in primary care, community medicine, and telemedicine in resource-limited settings. For more than fourteen years, he has worked in rural communities developing solutions to improve access to healthcare where specialized resources are scarce. His clinical experience inspired the creation of Global Care Network as an independent research initiative dedicated to the study, development, and validation of technologies applied to telemedicine, digital health, and clinical artificial intelligence.',
    'gcn.founder.about': 'About the Medical Director',
    'gcn.founder.why.title': 'Why Global Care Network Exists',
    'gcn.founder.why.p1': 'Global Care Network was created after years of clinical practice in rural and remote communities where access to healthcare was often limited by distance, lack of resources and limited access to specialist support.',
    'gcn.founder.why.p2': 'Rather than creating technology for its own sake, GCN develops practical healthcare solutions based on applied research that respond to real clinical needs observed in everyday medical practice.',
    'gcn.founder.interests': 'Professional Interests',
    'gcn.founder.i1': 'Primary Healthcare',
    'gcn.founder.i2': 'Healthy Ageing',
    'gcn.founder.i3': 'Telemedicine & Digital Health',
    'gcn.founder.i4': 'Clinical Artificial Intelligence',
    'gcn.founder.i5': 'Rural and Community Medicine',
    'gcn.founder.i6': 'Global Health',
    'gcn.founder.i7': 'Evidence-Based Medicine',
    'gcn.telemed.p1': 'We facilitate remote medical support and consultation for healthcare professionals in rural and hard-to-reach areas using asynchronous tools optimized for low connectivity.',
    'gcn.ai.p1': 'We research the responsible use of Clinical Artificial Intelligence as a support tool in triage and primary clinical decision-making, keeping human medical supervision as an irreplaceable core.',
    'gcn.partners.p1': 'We actively collaborate with universities, medical networks, and health professionals interested in the clinical and scientific validation of telemedicine tools.',
  }
};
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('ES');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['ES']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
